const field = (name, label, type = 'string', options = {}) => ({ name, label, type, ...options })

export const RESOURCE_GROUPS = [
  {
    key: 'platform',
    title: '平台基础',
    resources: ['user', 'notification', 'feedback'],
  },
  {
    key: 'agri',
    title: '农业生产',
    resources: ['landPlot', 'farmRecord', 'diseaseKnowledge', 'aiDetectRecord', 'yieldPrediction'],
  },
  {
    key: 'market',
    title: '流通销售',
    resources: ['marketPrice', 'product', 'order', 'traceRecord', 'buyer'],
  },
  {
    key: 'machinery',
    title: '农机共享',
    resources: ['machinery', 'machineryBooking', 'landTransfer'],
  },
  {
    key: 'disaster',
    title: '灾害应急',
    resources: ['disasterReport', 'weatherAlert', 'emergencyGuide', 'insuranceClaim'],
  },
  {
    key: 'policy',
    title: '政策党建',
    resources: ['policy', 'partyLesson', 'villageAffair', 'honorRecord', 'trainingCourse'],
  },
  {
    key: 'life',
    title: '生活服务',
    resources: ['jobInfo', 'tourismSpot', 'secondhandItem', 'helpRequest', 'envReport', 'loanProduct'],
  },
  {
    key: 'data',
    title: '数据管理',
    resources: ['annualReport', 'statReport', 'syncLog'],
  },
  {
    key: 'ai',
    title: 'AI 记录',
    resources: ['aiQaRecord', 'aiDetectRecord'],
  },
]

export const RESOURCE_CONFIGS = {
  user: {
    title: '用户与角色',
    model: 'user',
    searchFields: ['username', 'nickname', 'phone', 'realName', 'villageName'],
    listFields: ['id', 'username', 'nickname', 'role', 'phone', 'regionCode', 'points', 'growth', 'status', 'createdAt'],
    fields: [
      field('username', '用户名', 'string', { required: true }),
      field('password', '初始密码', 'password', { createOnly: true, placeholder: '不填则默认为 123456' }),
      field('nickname', '昵称'),
      field('phone', '手机号'),
      field('avatarUrl', '头像URL'),
      field('bannerUrl', '封面URL'),
      field('role', '角色', 'select', { options: ['FARMER', 'BIGFARMER', 'VILLAGE', 'EXPERT', 'MERCHANT', 'ADMIN'] }),
      field('regionCode', '行政区划'),
      field('villageName', '所属村'),
      field('realName', '实名'),
      field('points', '积分', 'int'),
      field('growth', '成长值', 'int', { placeholder: '累计成长值，跨阈值自动升级（新芽/幼苗/拔节/抽穗/金穗/丰仓）' }),
      field('isElderMode', '适老模式', 'boolean'),
      field('status', '状态', 'int'),
    ],
  },
  notification: {
    title: '通知公告',
    model: 'notification',
    searchFields: ['title', 'content', 'type'],
    listFields: ['id', 'type', 'title', 'userId', 'isRead', 'createdAt'],
    fields: [field('userId', '用户ID', 'int'), field('type', '类型'), field('title', '标题', 'string', { required: true }), field('content', '内容', 'textarea'), field('refId', '关联ID', 'int'), field('isRead', '已读', 'boolean')],
  },
  feedback: {
    title: '问题反馈',
    model: 'feedback',
    searchFields: ['category', 'content', 'contact', 'status'],
    listFields: ['id', 'category', 'content', 'status', 'contact', 'createdAt'],
    fields: [field('userId', '用户ID', 'int'), field('category', '分类'), field('content', '内容', 'textarea', { required: true }), field('contact', '联系方式'), field('images', '图片JSON', 'json'), field('status', '状态', 'select', { options: ['PENDING', 'REPLIED', 'CLOSED'] }), field('reply', '回复', 'textarea')],
  },
  landPlot: {
    title: '地块管理',
    model: 'landPlot',
    searchFields: ['plotName', 'cropType', 'soilType', 'regionCode'],
    listFields: ['id', 'plotName', 'userId', 'areaMu', 'cropType', 'soilType', 'regionCode', 'createdAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('plotName', '地块名称', 'string', { required: true }), field('areaMu', '面积亩', 'float'), field('boundaryGeojson', '边界GeoJSON', 'json'), field('cropType', '作物'), field('soilType', '土壤'), field('regionCode', '区域编码'), field('localUuid', '客户端UUID')],
  },
  farmRecord: {
    title: '农事记录',
    model: 'farmRecord',
    searchFields: ['recordType', 'cropType', 'content'],
    listFields: ['id', 'userId', 'plotId', 'recordType', 'cropType', 'cost', 'recordDate', 'createdAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('plotId', '地块ID', 'int'), field('recordType', '农事类型', 'select', { options: ['播种', '施肥', '打药', '灌溉', '收获', '其他'] }), field('cropType', '作物'), field('content', '内容', 'textarea'), field('cost', '成本', 'float'), field('images', '图片JSON', 'json'), field('recordDate', '记录日期', 'date'), field('localUuid', '客户端UUID')],
  },
  diseaseKnowledge: {
    title: '病害知识库',
    model: 'diseaseKnowledge',
    searchFields: ['diseaseName', 'cropType', 'category', 'symptoms'],
    listFields: ['id', 'diseaseName', 'cropType', 'category', 'modelLabel', 'createdAt'],
    fields: [field('diseaseName', '病害名称', 'string', { required: true }), field('cropType', '作物'), field('category', '分类'), field('symptoms', '症状', 'textarea'), field('cause', '原因', 'textarea'), field('prevention', '防治方案', 'textarea'), field('medicineAdvice', '用药建议', 'textarea'), field('coverImage', '封面图'), field('modelLabel', '模型标签')],
  },
  aiDetectRecord: {
    title: 'AI 识别记录',
    model: 'aiDetectRecord',
    searchFields: ['detectType', 'resultLabel', 'adviceText'],
    listFields: ['id', 'userId', 'detectType', 'resultLabel', 'confidence', 'isOffline', 'createdAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('detectType', '识别类型'), field('imageUrl', '图片URL', 'string', { required: true }), field('resultLabel', '结果标签'), field('confidence', '置信度', 'float'), field('adviceText', '建议', 'textarea'), field('isOffline', '终端生成', 'boolean'), field('feedback', '反馈', 'int'), field('localUuid', '客户端UUID')],
  },
  yieldPrediction: {
    title: '产量预测',
    model: 'yieldPrediction',
    searchFields: ['cropType'],
    listFields: ['id', 'plotId', 'cropType', 'predictedYield', 'predictDate', 'createdAt'],
    fields: [field('plotId', '地块ID', 'int', { required: true }), field('cropType', '作物'), field('predictedYield', '预测产量', 'float', { required: true }), field('confidenceLow', '区间下限', 'float'), field('confidenceHigh', '区间上限', 'float'), field('predictDate', '预测日期', 'date')],
  },
  marketPrice: {
    title: '行情价格',
    model: 'marketPrice',
    searchFields: ['productName', 'category', 'marketName', 'regionCode'],
    listFields: ['id', 'productName', 'category', 'marketName', 'price', 'unit', 'priceDate'],
    fields: [field('productName', '产品名', 'string', { required: true }), field('category', '分类'), field('marketName', '市场'), field('regionCode', '区域'), field('price', '价格', 'float', { required: true }), field('unit', '单位'), field('priceDate', '价格日期', 'date', { required: true })],
  },
  product: {
    title: '乡村集市商品',
    model: 'product',
    searchFields: ['title', 'category', 'description', 'traceCode'],
    listFields: ['id', 'title', 'sellerId', 'category', 'price', 'stock', 'status', 'createdAt'],
    fields: [field('sellerId', '卖家ID', 'int', { required: true }), field('title', '标题', 'string', { required: true }), field('category', '分类'), field('description', '描述', 'textarea'), field('price', '价格', 'float', { required: true }), field('unit', '单位'), field('stock', '库存', 'int'), field('images', '图片JSON', 'json'), field('traceCode', '溯源码'), field('regionCode', '区域'), field('status', '状态', 'int'), field('soldCount', '销量', 'int')],
  },
  order: {
    title: '订单管理',
    model: 'order',
    searchFields: ['orderNo', 'status', 'logisticsNo'],
    listFields: ['id', 'orderNo', 'buyerId', 'sellerId', 'productId', 'quantity', 'totalAmount', 'status', 'createdAt'],
    fields: [field('orderNo', '订单号', 'string', { required: true }), field('buyerId', '买家ID', 'int', { required: true }), field('sellerId', '卖家ID', 'int', { required: true }), field('productId', '商品ID', 'int', { required: true }), field('quantity', '数量', 'int', { required: true }), field('totalAmount', '总金额', 'float', { required: true }), field('status', '状态', 'select', { options: ['PENDING', 'PAID', 'SHIPPED', 'DONE', 'CANCELLED'] }), field('receiverInfo', '收货信息JSON', 'json'), field('logisticsNo', '物流单号'), field('remark', '备注', 'textarea')],
  },
  traceRecord: {
    title: '溯源记录',
    model: 'traceRecord',
    searchFields: ['traceCode', 'stage', 'description', 'operator'],
    listFields: ['id', 'traceCode', 'productId', 'stage', 'operator', 'recordTime'],
    fields: [field('traceCode', '溯源码', 'string', { required: true }), field('productId', '商品ID', 'int'), field('stage', '阶段', 'string', { required: true }), field('description', '描述', 'textarea'), field('images', '图片JSON', 'json'), field('operator', '操作人'), field('recordTime', '记录时间', 'date')],
  },
  buyer: {
    title: '收购站',
    model: 'buyer',
    searchFields: ['name', 'contactName', 'phone', 'address', 'products'],
    listFields: ['id', 'name', 'contactName', 'phone', 'address', 'regionCode', 'createdAt'],
    fields: [field('name', '名称', 'string', { required: true }), field('contactName', '联系人'), field('phone', '电话'), field('address', '地址'), field('regionCode', '区域'), field('lat', '纬度', 'float'), field('lng', '经度', 'float'), field('products', '收购品类')],
  },
  machinery: {
    title: '农机管理',
    model: 'machinery',
    searchFields: ['machineName', 'machineType', 'description', 'regionCode'],
    listFields: ['id', 'machineName', 'ownerId', 'machineType', 'dailyPrice', 'status', 'rating', 'createdAt'],
    fields: [field('ownerId', '机主ID', 'int', { required: true }), field('machineName', '农机名称', 'string', { required: true }), field('machineType', '类型'), field('dailyPrice', '日租金', 'float'), field('deposit', '押金', 'float'), field('regionCode', '区域'), field('totalHours', '累计小时', 'int'), field('images', '图片JSON', 'json'), field('description', '描述', 'textarea'), field('status', '状态', 'int'), field('rating', '评分', 'float')],
  },
  machineryBooking: {
    title: '农机预约',
    model: 'machineryBooking',
    searchFields: ['status', 'remark'],
    listFields: ['id', 'machineryId', 'renterId', 'startDate', 'endDate', 'totalAmount', 'status'],
    fields: [field('machineryId', '农机ID', 'int', { required: true }), field('renterId', '租用人ID', 'int', { required: true }), field('startDate', '开始日期', 'date', { required: true }), field('endDate', '结束日期', 'date', { required: true }), field('totalAmount', '总金额', 'float'), field('status', '状态', 'select', { options: ['PENDING', 'CONFIRMED', 'DONE', 'CANCELLED'] }), field('remark', '备注', 'textarea')],
  },
  landTransfer: {
    title: '土地流转',
    model: 'landTransfer',
    searchFields: ['title', 'location', 'transferType', 'status'],
    listFields: ['id', 'title', 'userId', 'areaMu', 'transferType', 'price', 'status', 'createdAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('title', '标题', 'string', { required: true }), field('areaMu', '面积亩', 'float'), field('regionCode', '区域'), field('location', '位置'), field('transferType', '流转类型'), field('price', '价格', 'float'), field('priceUnit', '价格单位'), field('duration', '期限'), field('description', '描述', 'textarea'), field('contactPhone', '电话'), field('status', '状态', 'select', { options: ['OPEN', 'DEALT', 'CLOSED'] })],
  },
  disasterReport: {
    title: '灾情上报',
    model: 'disasterReport',
    searchFields: ['disasterType', 'description', 'status', 'regionCode'],
    listFields: ['id', 'userId', 'disasterType', 'affectedArea', 'estimatedLoss', 'status', 'createdAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('disasterType', '灾害类型', 'string', { required: true }), field('plotId', '地块ID', 'int'), field('affectedArea', '受灾面积', 'float'), field('estimatedLoss', '预估损失', 'float'), field('description', '描述', 'textarea'), field('images', '图片JSON', 'json'), field('location', '位置JSON', 'json'), field('aiLossLevel', 'AI等级'), field('status', '状态', 'select', { options: ['REPORTED', 'REVIEWING', 'PROCESSED'] }), field('regionCode', '区域'), field('localUuid', '客户端UUID')],
  },
  weatherAlert: {
    title: '天气预警',
    model: 'weatherAlert',
    searchFields: ['alertType', 'alertLevel', 'title', 'regionCode'],
    listFields: ['id', 'alertType', 'alertLevel', 'title', 'regionCode', 'validFrom', 'validTo'],
    fields: [field('alertType', '预警类型', 'string', { required: true }), field('alertLevel', '等级', 'string', { required: true }), field('regionCode', '区域'), field('title', '标题', 'string', { required: true }), field('content', '内容', 'textarea'), field('defenseGuide', '防御指南', 'textarea'), field('validFrom', '开始时间', 'date', { required: true }), field('validTo', '结束时间', 'date', { required: true })],
  },
  emergencyGuide: {
    title: '应急预案',
    model: 'emergencyGuide',
    searchFields: ['title', 'disasterType', 'category', 'content'],
    listFields: ['id', 'title', 'disasterType', 'category', 'createdAt'],
    fields: [field('title', '标题', 'string', { required: true }), field('disasterType', '灾害类型', 'string', { required: true }), field('category', '分类'), field('content', '内容', 'textarea', { required: true }), field('steps', '步骤JSON', 'json')],
  },
  insuranceClaim: {
    title: '保险理赔',
    model: 'insuranceClaim',
    searchFields: ['claimType', 'aiAssessLevel', 'status', 'insurerContact'],
    listFields: ['id', 'userId', 'disasterReportId', 'claimType', 'estimatedAmount', 'status', 'createdAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('disasterReportId', '灾情ID', 'int'), field('claimType', '理赔类型'), field('estimatedAmount', '预估金额', 'float'), field('aiAssessLevel', 'AI评估等级'), field('assessDetail', '评估详情', 'textarea'), field('status', '状态', 'select', { options: ['SUBMITTED', 'ASSESSING', 'APPROVED', 'REJECTED'] }), field('insurerContact', '保险联系人')],
  },
  policy: {
    title: '政策管理',
    model: 'policy',
    searchFields: ['title', 'level', 'category', 'summary', 'publishOrg'],
    listFields: ['id', 'title', 'level', 'category', 'publishOrg', 'status', 'createdAt'],
    fields: [field('title', '标题', 'string', { required: true }), field('level', '级别'), field('category', '分类'), field('content', '正文', 'textarea', { required: true }), field('summary', '摘要', 'textarea'), field('publishOrg', '发布机构'), field('regionCode', '适用区域'), field('applyGuide', '申请指引', 'textarea'), field('validFrom', '有效开始', 'date'), field('validTo', '有效结束', 'date'), field('attachments', '附件JSON', 'json'), field('viewCount', '浏览量', 'int'), field('status', '状态', 'int')],
  },
  partyLesson: {
    title: '党建学习',
    model: 'partyLesson',
    searchFields: ['title', 'type', 'content'],
    listFields: ['id', 'title', 'type', 'pointsReward', 'publishDate', 'createdAt'],
    fields: [field('title', '标题', 'string', { required: true }), field('type', '类型'), field('content', '内容', 'textarea'), field('mediaUrl', '媒体URL'), field('pointsReward', '积分奖励', 'int'), field('publishDate', '发布日期', 'date')],
  },
  villageAffair: {
    title: '村务公开',
    model: 'villageAffair',
    searchFields: ['category', 'title', 'content', 'publishOrg'],
    listFields: ['id', 'category', 'title', 'regionCode', 'publishOrg', 'publishDate'],
    fields: [field('regionCode', '区域'), field('category', '分类', 'string', { required: true }), field('title', '标题', 'string', { required: true }), field('content', '内容', 'textarea'), field('attachments', '附件JSON', 'json'), field('publishOrg', '发布机构'), field('publishDate', '发布日期', 'date')],
  },
  honorRecord: {
    title: '文明乡风榜',
    model: 'honorRecord',
    searchFields: ['honoreeName', 'honorType', 'deed', 'status'],
    listFields: ['id', 'honoreeName', 'honorType', 'votes', 'status', 'createdAt'],
    fields: [field('regionCode', '区域'), field('honoreeName', '荣誉人', 'string', { required: true }), field('honorType', '荣誉类型'), field('deed', '事迹', 'textarea'), field('images', '图片JSON', 'json'), field('votes', '票数', 'int'), field('status', '状态', 'select', { options: ['PENDING', 'PUBLISHED'] })],
  },
  trainingCourse: {
    title: '培训课程',
    model: 'trainingCourse',
    searchFields: ['title', 'category', 'instructor', 'content'],
    listFields: ['id', 'title', 'category', 'instructor', 'durationMin', 'enrollCount', 'createdAt'],
    fields: [field('title', '标题', 'string', { required: true }), field('category', '分类'), field('cover', '封面'), field('instructor', '讲师'), field('content', '内容', 'textarea'), field('videoUrl', '视频URL'), field('durationMin', '时长分钟', 'int'), field('certName', '证书名'), field('enrollCount', '报名数', 'int')],
  },
  jobInfo: {
    title: '就业信息',
    model: 'jobInfo',
    searchFields: ['title', 'jobType', 'company', 'requirement'],
    listFields: ['id', 'title', 'jobType', 'company', 'salary', 'headcount', 'status', 'createdAt'],
    fields: [field('publisherId', '发布人ID', 'int'), field('title', '标题', 'string', { required: true }), field('jobType', '岗位类型'), field('company', '单位'), field('location', '地点'), field('salary', '薪资'), field('headcount', '人数', 'int'), field('requirement', '要求', 'textarea'), field('contactPhone', '电话'), field('regionCode', '区域'), field('status', '状态', 'select', { options: ['OPEN', 'CLOSED'] })],
  },
  tourismSpot: {
    title: '乡村旅游',
    model: 'tourismSpot',
    searchFields: ['name', 'spotType', 'address', 'description'],
    listFields: ['id', 'name', 'spotType', 'address', 'price', 'rating', 'createdAt'],
    fields: [field('name', '名称', 'string', { required: true }), field('spotType', '类型'), field('regionCode', '区域'), field('address', '地址'), field('description', '描述', 'textarea'), field('images', '图片JSON', 'json'), field('price', '价格', 'float'), field('phone', '电话'), field('promoText', '推广文案', 'textarea'), field('rating', '评分', 'float')],
  },
  secondhandItem: {
    title: '二手交易',
    model: 'secondhandItem',
    searchFields: ['title', 'category', 'description', 'status'],
    listFields: ['id', 'title', 'sellerId', 'category', 'price', 'status', 'createdAt'],
    fields: [field('sellerId', '卖家ID', 'int', { required: true }), field('title', '标题', 'string', { required: true }), field('category', '分类'), field('description', '描述', 'textarea'), field('price', '价格', 'float'), field('images', '图片JSON', 'json'), field('regionCode', '区域'), field('status', '状态', 'select', { options: ['ON_SALE', 'SOLD'] })],
  },
  helpRequest: {
    title: '邻里互助',
    model: 'helpRequest',
    searchFields: ['type', 'title', 'content', 'status'],
    listFields: ['id', 'type', 'title', 'userId', 'status', 'helperId', 'createdAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('type', '类型'), field('title', '标题', 'string', { required: true }), field('content', '内容', 'textarea'), field('regionCode', '区域'), field('contactPhone', '电话'), field('status', '状态', 'select', { options: ['OPEN', 'DONE'] }), field('helperId', '帮助人ID', 'int')],
  },
  envReport: {
    title: '环境举报',
    model: 'envReport',
    searchFields: ['problemType', 'description', 'status', 'handleResult'],
    listFields: ['id', 'problemType', 'userId', 'status', 'regionCode', 'createdAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('problemType', '问题类型'), field('description', '描述', 'textarea'), field('images', '图片JSON', 'json'), field('location', '位置'), field('regionCode', '区域'), field('status', '状态', 'select', { options: ['REPORTED', 'HANDLING', 'RESOLVED'] }), field('handleResult', '处理结果', 'textarea')],
  },
  loanProduct: {
    title: '贷款产品',
    model: 'loanProduct',
    searchFields: ['bankName', 'productName', 'requirement', 'description'],
    listFields: ['id', 'bankName', 'productName', 'interestRate', 'maxAmount', 'term', 'createdAt'],
    fields: [field('bankName', '银行', 'string', { required: true }), field('productName', '产品名', 'string', { required: true }), field('interestRate', '利率', 'float'), field('maxAmount', '最高额度', 'float'), field('term', '期限'), field('requirement', '要求', 'textarea'), field('description', '描述', 'textarea')],
  },
  annualReport: {
    title: '年度报告',
    model: 'annualReport',
    searchFields: ['summary', 'reportContent'],
    listFields: ['id', 'userId', 'year', 'totalIncome', 'totalCost', 'generatedByAi', 'createdAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('year', '年份', 'int', { required: true }), field('reportContent', '报告内容', 'textarea'), field('totalIncome', '总收入', 'float'), field('totalCost', '总成本', 'float'), field('summary', '摘要', 'textarea'), field('generatedByAi', 'AI生成', 'boolean')],
  },
  statReport: {
    title: '统计上报',
    model: 'statReport',
    searchFields: ['regionCode', 'statType', 'period', 'status'],
    listFields: ['id', 'regionCode', 'statType', 'year', 'period', 'status', 'createdAt'],
    fields: [field('regionCode', '区域'), field('reporterId', '上报人ID', 'int'), field('statType', '统计类型'), field('year', '年份', 'int', { required: true }), field('period', '周期'), field('dataJson', '数据JSON', 'json'), field('status', '状态', 'select', { options: ['DRAFT', 'SUBMITTED', 'CONFIRMED'] })],
  },
  syncLog: {
    title: '同步日志',
    model: 'syncLog',
    searchFields: ['tableName', 'operation', 'syncStatus', 'localUuid'],
    listFields: ['id', 'userId', 'tableName', 'operation', 'localUuid', 'syncStatus', 'syncedAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('tableName', '表名', 'string', { required: true }), field('operation', '操作', 'select', { options: ['INSERT', 'UPDATE', 'DELETE'] }), field('localUuid', '客户端UUID'), field('syncStatus', '同步状态', 'select', { options: ['SUCCESS', 'CONFLICT', 'FAILED'] }), field('conflictDetail', '冲突详情', 'textarea'), field('syncedAt', '同步时间', 'date')],
  },
  aiQaRecord: {
    title: 'AI 问答记录',
    model: 'aiQaRecord',
    searchFields: ['scene', 'question', 'answer', 'modelUsed'],
    listFields: ['id', 'userId', 'scene', 'question', 'modelUsed', 'isOffline', 'createdAt'],
    fields: [field('userId', '用户ID', 'int', { required: true }), field('scene', '场景'), field('question', '问题', 'textarea', { required: true }), field('answer', '答案', 'textarea', { required: true }), field('modelUsed', '模型'), field('isOffline', '终端生成', 'boolean'), field('referencesJson', '引用JSON', 'json')],
  },
}

export function getResourceConfig(key) {
  return RESOURCE_CONFIGS[key] || null
}

export function listResourceConfigs() {
  return Object.entries(RESOURCE_CONFIGS).map(([key, config]) => ({
    key,
    title: config.title,
    group: RESOURCE_GROUPS.find((group) => group.resources.includes(key))?.key || 'other',
  }))
}
