// 本文件由 backend/scripts/gen-feature-catalog.mjs 自动生成，请勿手工编辑。
// 重新生成：cd backend && node scripts/gen-feature-catalog.mjs --write
// 漂移检查：cd backend && node scripts/gen-feature-catalog.mjs --check
//
// 116f-F Flutter 功能墙（数据源 = backend/src/contracts/capabilities.js featureCatalog，gen-capabilities.mjs 生成产物；
// 驱动全局搜索（search_page）与全部服务（all_features_page）；tier/journey 用于 6 条主路径收敛）。
import 'package:flutter/material.dart';

enum FeatureTier { primary, tool, experimental }

class FeatureItem {
  final String id;
  final FeatureTier tier;
  final String? journey;
  final String name;
  final List<String> keywords;
  final String route;
  final IconData icon;
  final String section;

  const FeatureItem({
    required this.id,
    required this.tier,
    this.journey,
    required this.name,
    required this.keywords,
    required this.route,
    required this.icon,
    required this.section,
  });
}

const kFeatureSections = <String, String>{
  'agri': 'AI 农业生产',
  'market': '流通销售',
  'machinery': '农机共享',
  'disaster': '气象灾害',
  'policy': '惠农政策',
  'life': '乡村生活',
  'data': '数据管理',
  'ai': 'AI 助手',
};

const kFeatureCatalog = <FeatureItem>[
  FeatureItem(
      id: 'plant-care.diagnose',
      tier: FeatureTier.primary,
      journey: 'plant_care',
      name: '病虫害识别',
      keywords: ['病虫害', '识病', '拍照识别', '叶片', '植保'],
      route: '/agri/diagnose',
      icon: Icons.biotech_outlined,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.02',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '作物长势监测',
      keywords: ['长势', '监测', '作物'],
      route: '/agri',
      icon: Icons.eco_outlined,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.03',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '杂草识别',
      keywords: ['杂草', '除草'],
      route: '/agri',
      icon: Icons.grass_outlined,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.04',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '种子检测',
      keywords: ['种子', '发芽率'],
      route: '/agri',
      icon: Icons.spa_outlined,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.05',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '智能施肥',
      keywords: ['施肥', '肥料', '配方'],
      route: '/agri',
      icon: Icons.science_outlined,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.06',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '灌溉计划',
      keywords: ['灌溉', '浇水', '排灌'],
      route: '/agri',
      icon: Icons.water_drop_outlined,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.07',
      tier: FeatureTier.experimental,
      name: '产量预测',
      keywords: ['产量', '预测', '收成'],
      route: '/agri',
      icon: Icons.trending_up,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.08',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '农事日历',
      keywords: ['农事', '日历', '节气', '农时'],
      route: '/agri',
      icon: Icons.calendar_month_outlined,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.09',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '农药安全查询',
      keywords: ['农药', '安全间隔', '用药'],
      route: '/agri',
      icon: Icons.medication_outlined,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.10',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '地块管理',
      keywords: ['地块', 'GIS', '田块'],
      route: '/agri',
      icon: Icons.map_outlined,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.11',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '农事记录',
      keywords: ['农事记录', '打药', '记录'],
      route: '/agri',
      icon: Icons.note_alt_outlined,
      section: 'agri'),
  FeatureItem(
      id: 'agri.agri.12',
      tier: FeatureTier.experimental,
      name: '碳排放核算',
      keywords: ['碳排放', '碳', '减排'],
      route: '/agri',
      icon: Icons.co2,
      section: 'agri'),
  FeatureItem(
      id: 'agri.iot.13',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '智能物联',
      keywords: ['物联', '物联网', 'IoT', '传感器', '设备监测', '智能监测', '田间监测'],
      route: '/iot',
      icon: Icons.sensors_rounded,
      section: 'agri'),
  FeatureItem(
      id: 'agri.iot.14',
      tier: FeatureTier.tool,
      journey: 'plant_care',
      name: '设备联动',
      keywords: ['设备联动', '联动', '联动规则', '自动灌溉', '智能联动', '物联联动'],
      route: '/iot',
      icon: Icons.bolt_rounded,
      section: 'agri'),
  FeatureItem(
      id: 'market.market.15',
      tier: FeatureTier.tool,
      journey: 'market',
      name: '实时行情',
      keywords: ['行情', '价格', '报价'],
      route: '/market',
      icon: Icons.show_chart,
      section: 'market'),
  FeatureItem(
      id: 'market.trade',
      tier: FeatureTier.primary,
      journey: 'market',
      name: '乡村集市',
      keywords: ['集市', '商城', '买卖', '下单'],
      route: '/market',
      icon: Icons.storefront_outlined,
      section: 'market'),
  FeatureItem(
      id: 'market.market-service.17',
      tier: FeatureTier.experimental,
      name: '价格预测',
      keywords: ['价格预测', '趋势'],
      route: '/market/service',
      icon: Icons.query_stats,
      section: 'market'),
  FeatureItem(
      id: 'market.market-service.18',
      tier: FeatureTier.experimental,
      name: '期货行情',
      keywords: ['期货'],
      route: '/market/service',
      icon: Icons.candlestick_chart,
      section: 'market'),
  FeatureItem(
      id: 'market.market-service.19',
      tier: FeatureTier.experimental,
      name: '出口合规',
      keywords: ['出口', '合规', '外贸'],
      route: '/market/service',
      icon: Icons.public,
      section: 'market'),
  FeatureItem(
      id: 'market.market-service.20',
      tier: FeatureTier.tool,
      journey: 'market',
      name: '收购站地图',
      keywords: ['收购', '收购站'],
      route: '/market/service',
      icon: Icons.store_outlined,
      section: 'market'),
  FeatureItem(
      id: 'market.market-service.21',
      tier: FeatureTier.tool,
      journey: 'market',
      name: '农资团购',
      keywords: ['团购', '农资'],
      route: '/market/service',
      icon: Icons.groups_outlined,
      section: 'market'),
  FeatureItem(
      id: 'market.market-service.22',
      tier: FeatureTier.experimental,
      name: 'AI 质量分级',
      keywords: ['质量分级', '分级', '品控'],
      route: '/market/service',
      icon: Icons.grade_outlined,
      section: 'market'),
  FeatureItem(
      id: 'market.market-service.23',
      tier: FeatureTier.experimental,
      name: '直播话术',
      keywords: ['直播', '话术', '带货'],
      route: '/market/service',
      icon: Icons.mic_none_outlined,
      section: 'market'),
  FeatureItem(
      id: 'market.market-service.24',
      tier: FeatureTier.experimental,
      name: '包装文案',
      keywords: ['包装', '文案'],
      route: '/market/service',
      icon: Icons.inventory_2_outlined,
      section: 'market'),
  FeatureItem(
      id: 'market.market-service.25',
      tier: FeatureTier.tool,
      journey: 'market',
      name: '溯源码',
      keywords: ['溯源', '追溯'],
      route: '/market/service',
      icon: Icons.qr_code_2,
      section: 'market'),
  FeatureItem(
      id: 'market.market-service.26',
      tier: FeatureTier.tool,
      journey: 'market',
      name: '物流查询',
      keywords: ['物流', '快递', '运输'],
      route: '/market/service',
      icon: Icons.local_shipping_outlined,
      section: 'market'),
  FeatureItem(
      id: 'machinery.booking',
      tier: FeatureTier.primary,
      journey: 'machinery',
      name: '农机租赁',
      keywords: ['农机', '租赁', '拖拉机', '收割机'],
      route: '/machinery',
      icon: Icons.agriculture_outlined,
      section: 'machinery'),
  FeatureItem(
      id: 'machinery.machinery-service.28',
      tier: FeatureTier.tool,
      journey: 'machinery',
      name: '维保提醒',
      keywords: ['维保', '保养'],
      route: '/machinery/service',
      icon: Icons.build_outlined,
      section: 'machinery'),
  FeatureItem(
      id: 'machinery.machinery-service.29',
      tier: FeatureTier.tool,
      journey: 'machinery',
      name: '故障诊断',
      keywords: ['故障', '诊断', '维修'],
      route: '/machinery/service',
      icon: Icons.handyman_outlined,
      section: 'machinery'),
  FeatureItem(
      id: 'machinery.machinery-service.30',
      tier: FeatureTier.tool,
      journey: 'machinery',
      name: '作业轨迹',
      keywords: ['轨迹', '作业'],
      route: '/machinery/service',
      icon: Icons.route_outlined,
      section: 'machinery'),
  FeatureItem(
      id: 'machinery.machinery-service.31',
      tier: FeatureTier.tool,
      journey: 'machinery',
      name: '成本核算',
      keywords: ['成本', '核算'],
      route: '/machinery/service',
      icon: Icons.calculate_outlined,
      section: 'machinery'),
  FeatureItem(
      id: 'machinery.machinery-service.32',
      tier: FeatureTier.tool,
      journey: 'machinery',
      name: '土地流转',
      keywords: ['土地流转', '流转'],
      route: '/machinery/service',
      icon: Icons.swap_horiz,
      section: 'machinery'),
  FeatureItem(
      id: 'machinery.machinery-service.33',
      tier: FeatureTier.tool,
      journey: 'machinery',
      name: '机手认证',
      keywords: ['机手', '认证'],
      route: '/machinery/service',
      icon: Icons.verified_user_outlined,
      section: 'machinery'),
  FeatureItem(
      id: 'machinery.machinery-service.34',
      tier: FeatureTier.tool,
      journey: 'machinery',
      name: '农机保险',
      keywords: ['农机保险', '保险'],
      route: '/machinery/service',
      icon: Icons.shield_outlined,
      section: 'machinery'),
  FeatureItem(
      id: 'disaster.disaster.35',
      tier: FeatureTier.tool,
      journey: 'disaster',
      name: '极端天气预警',
      keywords: ['天气', '预警', '气象', '暴雨'],
      route: '/disaster',
      icon: Icons.thunderstorm_outlined,
      section: 'disaster'),
  FeatureItem(
      id: 'disaster.report',
      tier: FeatureTier.primary,
      journey: 'disaster',
      name: '灾情上报',
      keywords: ['灾情', '上报', '受灾'],
      route: '/disaster',
      icon: Icons.report_outlined,
      section: 'disaster'),
  FeatureItem(
      id: 'disaster.disaster.37',
      tier: FeatureTier.tool,
      journey: 'disaster',
      name: '保险理赔',
      keywords: ['理赔', '保险'],
      route: '/disaster',
      icon: Icons.assignment_turned_in_outlined,
      section: 'disaster'),
  FeatureItem(
      id: 'disaster.disaster.38',
      tier: FeatureTier.tool,
      journey: 'disaster',
      name: '应急预案',
      keywords: ['应急', '预案'],
      route: '/disaster',
      icon: Icons.emergency_outlined,
      section: 'disaster'),
  FeatureItem(
      id: 'disaster.disaster.39',
      tier: FeatureTier.experimental,
      name: '冻害防护',
      keywords: ['冻害', '霜冻', '防冻'],
      route: '/disaster',
      icon: Icons.ac_unit,
      section: 'disaster'),
  FeatureItem(
      id: 'disaster.disaster.40',
      tier: FeatureTier.experimental,
      name: '火险预警',
      keywords: ['火险', '火灾'],
      route: '/disaster',
      icon: Icons.local_fire_department_outlined,
      section: 'disaster'),
  FeatureItem(
      id: 'disaster.disaster.41',
      tier: FeatureTier.experimental,
      name: '干旱指数',
      keywords: ['干旱', '旱情'],
      route: '/disaster',
      icon: Icons.wb_sunny_outlined,
      section: 'disaster'),
  FeatureItem(
      id: 'disaster.disaster.42',
      tier: FeatureTier.tool,
      journey: 'disaster',
      name: '一键求助',
      keywords: ['求助', 'SOS', '紧急'],
      route: '/disaster',
      icon: Icons.sos_outlined,
      section: 'disaster'),
  FeatureItem(
      id: 'policy.policy.43',
      tier: FeatureTier.tool,
      journey: 'policy',
      name: '政策推送',
      keywords: ['政策', '惠农', '三农'],
      route: '/policy',
      icon: Icons.account_balance_outlined,
      section: 'policy'),
  FeatureItem(
      id: 'policy.subsidy',
      tier: FeatureTier.primary,
      journey: 'policy',
      name: '补贴申请',
      keywords: ['补贴', '申请', '补助'],
      route: '/policy/service',
      icon: Icons.fact_check_outlined,
      section: 'policy'),
  FeatureItem(
      id: 'policy.policy-service.45',
      tier: FeatureTier.tool,
      journey: 'policy',
      name: '政策 AI 问答',
      keywords: ['政策问答', '咨询'],
      route: '/policy/service',
      icon: Icons.question_answer_outlined,
      section: 'policy'),
  FeatureItem(
      id: 'policy.policy.46',
      tier: FeatureTier.tool,
      journey: 'policy',
      name: '党建学习',
      keywords: ['党建', '学习', '打卡'],
      route: '/policy',
      icon: Icons.flag_outlined,
      section: 'policy'),
  FeatureItem(
      id: 'policy.policy.47',
      tier: FeatureTier.tool,
      journey: 'policy',
      name: '村务公开',
      keywords: ['村务', '公开'],
      route: '/policy',
      icon: Icons.campaign_outlined,
      section: 'policy'),
  FeatureItem(
      id: 'policy.policy.48',
      tier: FeatureTier.tool,
      journey: 'policy',
      name: '文明乡风榜',
      keywords: ['文明', '乡风', '榜'],
      route: '/policy',
      icon: Icons.emoji_events_outlined,
      section: 'policy'),
  FeatureItem(
      id: 'policy.policy-service.49',
      tier: FeatureTier.tool,
      journey: 'policy',
      name: '法律咨询',
      keywords: ['法律', '普法', '维权'],
      route: '/policy/service',
      icon: Icons.gavel_outlined,
      section: 'policy'),
  FeatureItem(
      id: 'policy.policy-service.50',
      tier: FeatureTier.tool,
      journey: 'policy',
      name: '职业农民培训',
      keywords: ['培训', '职业农民', '课程'],
      route: '/policy/service',
      icon: Icons.school_outlined,
      section: 'policy'),
  FeatureItem(
      id: 'life.life.51',
      tier: FeatureTier.tool,
      journey: 'life_services',
      name: '村医问诊',
      keywords: ['村医', '问诊', '看病', '健康'],
      route: '/life',
      icon: Icons.medical_services_outlined,
      section: 'life'),
  FeatureItem(
      id: 'life.life.52',
      tier: FeatureTier.tool,
      journey: 'life_services',
      name: '快递代收',
      keywords: ['快递', '代收', '取件'],
      route: '/life',
      icon: Icons.local_post_office_outlined,
      section: 'life'),
  FeatureItem(
      id: 'life.life.53',
      tier: FeatureTier.tool,
      journey: 'life_services',
      name: '就业平台',
      keywords: ['就业', '招工', '找工作'],
      route: '/life',
      icon: Icons.work_outline,
      section: 'life'),
  FeatureItem(
      id: 'life.life.54',
      tier: FeatureTier.tool,
      journey: 'life_services',
      name: '水电气缴费',
      keywords: ['缴费', '水电', '水费', '电费'],
      route: '/life',
      icon: Icons.receipt_long_outlined,
      section: 'life'),
  FeatureItem(
      id: 'life.life.55',
      tier: FeatureTier.experimental,
      name: '乡村旅游',
      keywords: ['旅游', '农家乐'],
      route: '/life',
      icon: Icons.landscape_outlined,
      section: 'life'),
  FeatureItem(
      id: 'life.life.56',
      tier: FeatureTier.tool,
      journey: 'life_services',
      name: '养老关爱',
      keywords: ['养老', '关爱', '老人'],
      route: '/life',
      icon: Icons.elderly,
      section: 'life'),
  FeatureItem(
      id: 'life.life.57',
      tier: FeatureTier.experimental,
      name: '农业贷款',
      keywords: ['贷款', '金融', '借款'],
      route: '/life',
      icon: Icons.savings_outlined,
      section: 'life'),
  FeatureItem(
      id: 'life.life.58',
      tier: FeatureTier.tool,
      journey: 'life_services',
      name: '教育辅导',
      keywords: ['教育', '辅导', '上学'],
      route: '/life',
      icon: Icons.menu_book_outlined,
      section: 'life'),
  FeatureItem(
      id: 'life.life.59',
      tier: FeatureTier.tool,
      journey: 'life_services',
      name: '邻里互助',
      keywords: ['邻里', '互助', '帮忙'],
      route: '/life',
      icon: Icons.handshake_outlined,
      section: 'life'),
  FeatureItem(
      id: 'life.life.60',
      tier: FeatureTier.tool,
      journey: 'life_services',
      name: '二手交易',
      keywords: ['二手', '闲置', '转让'],
      route: '/life',
      icon: Icons.sell_outlined,
      section: 'life'),
  FeatureItem(
      id: 'life.life.61',
      tier: FeatureTier.experimental,
      name: '民俗记录',
      keywords: ['民俗', '文化', '非遗'],
      route: '/life',
      icon: Icons.festival_outlined,
      section: 'life'),
  FeatureItem(
      id: 'life.life.62',
      tier: FeatureTier.tool,
      journey: 'life_services',
      name: '环境举报',
      keywords: ['环境', '举报', '污染'],
      route: '/life',
      icon: Icons.eco,
      section: 'life'),
  FeatureItem(
      id: 'village.dashboard',
      tier: FeatureTier.primary,
      journey: 'village',
      name: '农情数据看板',
      keywords: ['看板', '数据', '农情', '驾驶舱'],
      route: '/data',
      icon: Icons.insights_outlined,
      section: 'data'),
  FeatureItem(
      id: 'data.data-service.64',
      tier: FeatureTier.tool,
      journey: 'village',
      name: '农事年度报告',
      keywords: ['年度报告', '报告'],
      route: '/data/service',
      icon: Icons.event_note_outlined,
      section: 'data'),
  FeatureItem(
      id: 'data.data-service.65',
      tier: FeatureTier.tool,
      journey: 'village',
      name: '统计上报',
      keywords: ['统计', '上报'],
      route: '/data/service',
      icon: Icons.upload_file_outlined,
      section: 'data'),
  FeatureItem(
      id: 'data.data-service.66',
      tier: FeatureTier.tool,
      journey: 'village',
      name: '数据同步',
      keywords: ['同步', '队列'],
      route: '/data/service',
      icon: Icons.sync_alt,
      section: 'data'),
  FeatureItem(
      id: 'data.data.67',
      tier: FeatureTier.experimental,
      name: '遥感分析',
      keywords: ['遥感', '卫星', 'NDVI'],
      route: '/data',
      icon: Icons.satellite_alt_outlined,
      section: 'data'),
  FeatureItem(
      id: 'ai.ai-chat.68',
      tier: FeatureTier.tool,
      journey: 'assistant',
      name: 'AI 智能问答',
      keywords: ['AI', '问答', '助手', '聊天'],
      route: '/ai/chat/new',
      icon: Icons.smart_toy_outlined,
      section: 'ai'),
  FeatureItem(
      id: 'ai.agri-diagnose.69',
      tier: FeatureTier.tool,
      journey: 'assistant',
      name: '拍照识病',
      keywords: ['拍照', '识病', '植保'],
      route: '/agri/diagnose',
      icon: Icons.center_focus_strong_outlined,
      section: 'ai'),
  FeatureItem(
      id: 'ai.ai.70',
      tier: FeatureTier.tool,
      journey: 'assistant',
      name: 'AI 对话历史',
      keywords: ['历史', '对话', '记录'],
      route: '/ai',
      icon: Icons.history,
      section: 'ai'),
];

final kPrimaryFeatures = kFeatureCatalog
    .where((f) => f.tier == FeatureTier.primary)
    .toList(growable: false);

final kToolFeatures = kFeatureCatalog
    .where((f) => f.tier == FeatureTier.tool)
    .toList(growable: false);

final kExperimentalFeatures = kFeatureCatalog
    .where((f) => f.tier == FeatureTier.experimental)
    .toList(growable: false);
