export const API_CATALOG = [
  {
    group: '系统与驾驶舱',
    items: [
      {
        key: 'dashboard',
        name: '运营驾驶舱',
        method: 'GET',
        path: '/data/dashboard',
        auth: false,
        description: '读取首页统计卡片、作物面积分布和离线就绪状态。',
        bodyNote: '无需请求体。',
      },
      {
        key: 'ai-status',
        name: '本地 AI 状态',
        method: 'GET',
        path: '/ai/status',
        auth: false,
        description: '检查 Ollama、本地规则兜底和离线知识库状态。',
        bodyNote: '无需请求体。',
      },
      {
        key: 'global-search',
        name: '全局搜索',
        method: 'GET',
        path: '/search?keyword=玉米',
        auth: false,
        description: '跨政策、农技、商品和生活服务做统一检索。',
        bodyNote: '通过 query 参数传 keyword。',
      },
    ],
  },
  {
    group: '农业生产',
    items: [
      {
        key: 'plot-list',
        name: '地块列表',
        method: 'GET',
        path: '/agri/plot/list?pageNum=1&pageSize=10',
        auth: false,
        description: '查询本地 SQLite 中的地块档案，供农事记录和 GIS 管理使用。',
        bodyNote: '无需请求体。',
      },
      {
        key: 'farm-record-create',
        name: '新增农事记录',
        method: 'POST',
        path: '/agri/record',
        auth: false,
        description: '创建播种、施肥、打药、灌溉、收获等农事记录。',
        bodyNote: 'recordType、cropType、content、recordDate 是创建农事记录的关键字段。',
        body: {
          userId: 1,
          plotId: 1,
          recordType: '施肥',
          cropType: '玉米',
          content: '追施复合肥 20 公斤，土壤墒情良好',
          cost: 86,
          recordDate: '2026-05-21',
          localUuid: 'demo-farm-record-001',
        },
      },
      {
        key: 'yield-predict',
        name: '产量预测',
        method: 'POST',
        path: '/agri/yield/predict',
        auth: false,
        description: '使用本地规则/轻量模型根据地块和作物信息返回产量预测。',
        bodyNote: 'plotId 与 cropType 用于定位地块和作物，areaMu 可辅助估算。',
        body: {
          plotId: 1,
          cropType: '玉米',
          areaMu: 8.5,
        },
      },
    ],
  },
  {
    group: '流通销售',
    items: [
      {
        key: 'market-price',
        name: '行情查询',
        method: 'GET',
        path: '/market/price?productName=玉米&pageNum=1&pageSize=10',
        auth: false,
        description: '查询本地行情缓存与历史价格数据。',
        bodyNote: '通过 query 参数传 productName、category、regionCode。',
      },
      {
        key: 'market-products',
        name: '商品列表',
        method: 'GET',
        path: '/market/product/list?pageNum=1&pageSize=10',
        auth: false,
        description: '查询乡村集市商品。',
        bodyNote: '无需请求体。',
      },
      {
        key: 'package-copy',
        name: '包装文案生成',
        method: 'POST',
        path: '/market/package/generate',
        auth: true,
        description: '调用本地 AI 或兜底模板生成农产品包装文案。',
        bodyNote: 'productName、feature、targetMarket 越完整，生成结果越稳定。',
        body: {
          productName: '高山玉米',
          feature: '海拔高、昼夜温差大、口感清甜',
          targetMarket: '社区团购',
        },
      },
    ],
  },
  {
    group: '政策党建与 AI',
    items: [
      {
        key: 'policy-list',
        name: '政策列表',
        method: 'GET',
        path: '/policy/list?pageNum=1&pageSize=10',
        auth: false,
        description: '读取国家、省、县三级惠农政策。',
        bodyNote: '可通过 category、level、keyword 查询。',
      },
      {
        key: 'policy-ask',
        name: '政策 AI 问答',
        method: 'POST',
        path: '/policy/ai/ask',
        auth: true,
        description: '基于本地 RAG/SQLite 知识库回答政策问题，断网可用。',
        bodyNote: 'question 必填，regionCode 可用于区域政策过滤。',
        body: {
          question: '种植玉米有没有补贴，怎么申请？',
          regionCode: '440100',
        },
      },
      {
        key: 'ai-chat',
        name: '通用 AI 对话',
        method: 'POST',
        path: '/ai/chat',
        auth: false,
        description: '本地 Ollama 优先，失败时使用内置规则兜底。',
        bodyNote: 'scene 可传 agri、policy、legal、general。',
        body: {
          scene: 'agri',
          question: '玉米叶片发黄可能是什么原因？',
        },
      },
    ],
  },
  {
    group: '灾害应急与数据',
    items: [
      {
        key: 'disaster-alert',
        name: '天气预警列表',
        method: 'GET',
        path: '/disaster/alert/list?pageNum=1&pageSize=10',
        auth: false,
        description: '查询村镇级天气预警和灾害提醒。',
        bodyNote: '无需请求体。',
      },
      {
        key: 'data-sync',
        name: '离线同步',
        method: 'POST',
        path: '/data/sync',
        auth: false,
        description: '模拟 Flutter 端离线队列回放，把本地操作同步到后端。',
        bodyNote: 'items 为待同步操作数组，localUuid 用于去重。',
        body: {
          deviceId: 'demo-device-admin',
          items: [
            {
              tableName: 'farm_record',
              operation: 'INSERT',
              localUuid: 'demo-sync-record-001',
              payload: {
                recordType: '灌溉',
                content: '离线补录灌溉一次',
              },
            },
          ],
        },
      },
      {
        key: 'sync-status',
        name: '同步状态',
        method: 'GET',
        path: '/data/sync/status',
        auth: false,
        description: '读取同步队列、冲突与最近同步状态。',
        bodyNote: '无需请求体。',
      },
    ],
  },
  {
    group: '后台治理',
    items: [
      {
        key: 'switch-list',
        name: 'API 开关列表',
        method: 'GET',
        path: '/admin/api-switch/list?pageNum=1&pageSize=10',
        auth: true,
        description: '查看可动态开启/关闭的后端能力。',
        bodyNote: '通过 keyword、category、enabled query 参数过滤。',
      },
      {
        key: 'operation-logs',
        name: '操作日志列表',
        method: 'GET',
        path: '/admin/operation-log/list?pageNum=1&pageSize=10',
        auth: true,
        description: '查看非 GET API 的审计日志。',
        bodyNote: '通过 module、userId、keyword query 参数过滤。',
      },
      {
        key: 'rate-limit',
        name: '限流快照',
        method: 'GET',
        path: '/admin/rate-limit/status',
        auth: true,
        description: '查看内存限流策略与当前计数。',
        bodyNote: '无需请求体。',
      },
    ],
  },
]

export function flatApiCatalog() {
  return API_CATALOG.flatMap((group) => group.items.map((item) => ({ ...item, group: group.group })))
}
